### ISSUE TITLE
你好，Golin-master项目成功了么

### ISSUE THREAD

**Issue by h1768101** [aoeeeeeee/First#1]

**Comment by aoeeeeeee** [comment]
还没有，用vscode跑的，还在配cgo





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aoeeeeeee/First"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月29日(星期一) 晚上10:04
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[aoeeeeeee/First] 你好，Golin-master项目成功了么 (Issue #1)

**Comment by aoeeeeeee** [comment]
网页界面在这里！不过运行成功后，我也没有web页面。单独将html打开之后，选择功能，不能跳转到相应页面




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aoeeeeeee/First"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月29日(星期一) 晚上10:04
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[aoeeeeeee/First] 你好，Golin-master项目成功了么 (Issue #1)

**Comment by aoeeeeeee** [comment]
你好，解决了！加参数就行
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aoeeeeeee/First"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月29日(星期一) 晚上10:04
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[aoeeeeeee/First] 你好，Golin-master项目成功了么 (Issue #1)

**Comment by aoeeeeeee** [comment]
师傅你好！打扰啦！纯小白参考这个项目做毕设，请问方便加个联系方式一起学习吗？



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aoeeeeeee/First"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月29日(星期一) 晚上10:04
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[aoeeeeeee/First] 你好，Golin-master项目成功了么 (Issue #1)

**Comment by h1768101** [comment]
加vx&nbsp; 17721509645



黄俊杰
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aoeeeeeee/First"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月6日(星期二) 上午10:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [aoeeeeeee/First] 你好，Golin-master项目成功了么 (Issue #1)





 师傅你好！打扰啦！纯小白参考这个项目做毕设，请问方便加个联系方式一起学习吗？ 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "aoeeeeeee/First"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2024年1月29日(星期一) 晚上10:04 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;; 
 主题:&amp;nbsp;[aoeeeeeee/First] 你好，Golin-master项目成功了么 (Issue #1)
